name: XGuardian - SAST Scan (WebGoat)

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  sast-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: XGuardian SAST Scan
        uses: xguardian-actions/actions/sast@development
        with:
          token: ${{ secrets.XGUARDIAN_TOKEN }}
          app_name: "TSTCentralDeRiscos"
          app_id: "1830"
          pdf: "true"
          get_scan_id: "true"
